name: CancerCausality
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run-tests
        run: |
          python -m unittest

      - name: Test Results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Test Results" >> report.md
          cat tests/results.txt >> report.md
          cml-send-comment report.md
